# **Hoja de Trucos: NumPy**

## **NumPy para Ciencia de Datos en Python**

## **Creación de Arrays**
### Creación básica de arrays:

In [70]:
import numpy as np

a = np.array([1, 2, 3])  # Array unidimensional
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)  # Array bidimensional
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], dtype=float)  # Array tridimensional

### Arrays especiales:

In [2]:
np.zeros((3, 4))  # Array de ceros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones((2, 3, 4), dtype=np.int16)  # Array de unos

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [4]:
d = np.arange(10, 25, 5)  # Valores espaciados con paso

In [5]:
np.linspace(0, 2, 9)  # Valores espaciados uniformemente

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [6]:
e = np.full((2, 2), 7)  # Array constante con el valor 7

In [7]:
f = np.eye(2)  # Matriz identidad 2x2

In [8]:
np.random.random((2, 2))  # Array con valores aleatorios

array([[0.82639335, 0.85466515],
       [0.45184973, 0.8739764 ]])

In [9]:
np.empty((3, 2))  # Array vacío

array([[8.78954729e-312, 8.78954729e-312],
       [8.78954729e-312, 1.86921822e-306],
       [1.37961709e-306, 3.23790862e-319]])

## **Inspección del Array**

In [10]:
b.shape  # Dimensiones del array

(2, 3)

In [11]:
len(a)  # Longitud del array

3

In [12]:
c.ndim  # Número de dimensiones

3

In [13]:
e.size  # Número total de elementos

4

In [14]:
b.dtype  # Tipo de datos de los elementos

dtype('float64')

In [15]:
b.dtype.name  # Nombre del tipo de datos

'float64'

In [16]:
b.astype(int)  # Convertir a otro tipo

array([[1, 2, 3],
       [4, 5, 6]])

### Tipos de datos

In [17]:
np.int64 # Tipos enteros de 64 bits con signo

numpy.int64

In [18]:
np.float32  # Coma flotante de doble precisión estándar

numpy.float32

In [19]:
np.complex_ # Números complejos representados por 128 puntos flotantes

numpy.complex128

In [20]:
np.bool_ # Tipo booleano que almacena valores VERDADERO y FALSO

numpy.bool_

In [21]:
np.object_ # Tipo de objeto de Python

numpy.object_

In [22]:
np.string_ # Tipo de cadena de longitud fija

numpy.bytes_

In [23]:
np.unicode_ # Tipo Unicode de longitud fija

numpy.str_

## **Matemáticas con Arrays**
### Operaciones aritméticas:

In [24]:
b + a # Suma

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [25]:
np.add(b,a) # Suma

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [26]:
g = a - b # Resta

In [27]:
np.subtract(a,b) # Resta

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [28]:
a * b # Multiplicación

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [29]:
np.multiply(a,b) # Multiplicación

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [30]:
a / b # División

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [31]:
np.divide(a,b) # División

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [32]:
np.exp(b) # Exponencial

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [33]:
np.sqrt(b) # Raíz cuadrada

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [34]:
np.sin(a) # Imprimir senos de un array

array([0.84147098, 0.90929743, 0.14112001])

In [35]:
np.cos(b) # Coseno elemento por elemento

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [36]:
np.log(a) # Logaritmo natural elemento por elemento

array([0.        , 0.69314718, 1.09861229])

In [37]:
e.dot(f) # Producto escalar

array([[7., 7.],
       [7., 7.]])

## **Subconjuntos, Cortes e Indexación**
### Selección de elementos:

In [38]:
a[2]  # Elemento en el índice 2

3

In [39]:
b[1, 2]  # Elemento en fila 1, columna 2

6.0

### Cortes (slicing):

In [40]:
a[0:2]  # Elementos en los índices 0 y 1

array([1, 2])

In [41]:
b[0:2, 1]  # Elementos en filas 0 y 1, columna 1

array([2., 5.])

In [42]:
b[:1]  # Todos los elementos de la fila 0

array([[1.5, 2. , 3. ]])

### Indexación booleana:

In [43]:
a[a < 2]  # Elementos de `a` menores a 2

array([1])

### Indexación avanzada:

In [44]:
b[[1, 0, 1, 0], [0, 1, 2, 0]]  # Elementos en posiciones específicas

array([4. , 2. , 6. , 1.5])

### Comparación

In [45]:
a = b # Comparación elemento por elemento

In [46]:
a < 2 # #Comparación elemento por elemento

array([[ True, False, False],
       [False, False, False]])

In [47]:
np.array_equal(a,b) # Comparación de matriz por matriz

True

### Funciones agregadas

In [48]:
a.sum()  # Suma

21.5

In [49]:
a.min()  # Mínimo

1.5

In [50]:
b.max(axis=0)  # Máximo por fila

array([4., 5., 6.])

In [51]:
b.cumsum(axis=1)  # Suma acumulativa

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [52]:
a.mean()  # Promedio

3.5833333333333335

In [53]:
np.median(b)  # Mediana

3.5

In [54]:
np.corrcoef(a)  # Coeficiente de correlación

array([[1.        , 0.98198051],
       [0.98198051, 1.        ]])

In [55]:
np.std(b)  # Desviación estándar

1.5920810978785667

## Copiando arrays

In [56]:
h = a.view() # Crear una vista de la matriz con los mismos datos

In [57]:
np.copy(a) # Crear una copia de la matriz

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [58]:
h = a.copy() # Crear una copia profunda de la matriz

## Ordenar arrays

In [59]:
a.sort() # Ordenar un array

In [60]:
c.sort(axis=0) # Ordenar los elementos del eje de un array

## **Manipulación de Arrays**

### Transposición:

In [61]:
i = np.transpose(b)  # Transponer un array

In [62]:
i.T # Permutar dimensiones de un array

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

### Cambio de forma:

In [63]:
b.ravel() # Aplanar el array

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [64]:
g.reshape(3, -2)  # Cambia la forma sin alterar los datos

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

### Agregar y eliminar elementos:

In [65]:
h.resize((2,6)) # #Devuelve un nuevo array con forma (2,6)

In [66]:
np.append(h, g)  # Agregar elementos

array([ 1.5,  2. ,  3. ,  4. ,  5. ,  6. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [67]:
np.insert(a, 1, 5)  # Insertar elementos

array([1.5, 5. , 2. , 3. , 4. , 5. , 6. ])

In [68]:
np.delete(a, [1])  # Eliminar elementos

array([1.5, 3. , 4. , 5. , 6. ])

### Combinar arrays

In [ ]:
a = np.array([1, 2, 3])  # Array unidimensional
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)  # Array bidimensional

In [71]:
np.concatenate((a, d), axis=0)  # Concatenar arrays


array([ 1,  2,  3, 10, 15, 20])

In [72]:
np.vstack((a,b)) # Apilar arrays verticalmente (filas por filas)

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [73]:
np.r_[e,f] # Apilar arrays verticalmente (filas por filas)

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [74]:
np.hstack((e,f)) # Apilar arrays horizontalmente (columnas por columna)

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [75]:
np.column_stack((a,d)) # Crear arrays apilados por columnas

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [76]:
np.c_[a,d] # Crear arrays apilados por columnas

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

### División de arrays

In [77]:
np.hsplit(a, 3)  # Dividir horizontalmente en el tercer índice

[array([1]), array([2]), array([3])]

In [78]:

np.vsplit(c, 2)  # Dividir verticalmente en el segundo índice

[array([[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]]]),
 array([[[3., 2., 1.],
         [4., 5., 6.]]])]

## **Guardado y Carga de Archivos**
### Guardar y cargar en formato binario:

In [79]:
np.save('archivo.npy', a)  # Guardar en archivo binario

In [80]:
np.load('archivo.npy')  # Cargar archivo binario

array([1, 2, 3])

### Guardar y cargar en texto:

In [81]:
np.savetxt('archivo.txt', a, delimiter=',')  # Guardar como texto

In [82]:
np.loadtxt('archivo.txt', delimiter=',')  # Cargar archivo de texto

array([1., 2., 3.])